#!/bin/bash

APP_PATH=/usr/share/droid-at-screen-ng
CONFIG_PATH=/etc/droid-at-screen-ng
MAIN_CLASS=com.ribomation.droidAtScreen.DroidAtScreenApplication

classpath=$(java-config --classpath=log4j,ddmlib)

while [[ $classpath = *::* ]]; do classpath="${classpath//::/:}"; done
classpath=${classpath%:}
classpath=${classpath#:}

java -cp "${CONFIG_PATH}:${APP_PATH}/classes:${APP_PATH}/resources:${classpath}" "${MAIN_CLASS}"
