#!/bin/sh
#
# Author: Yuri <nE0sIghT> Konotopov
# License: GNU GPL v3 or any later version
#

source /lib/gentoo/functions.sh
source /usr/$(get_libdir)/vortex-build/vortex-functions.sh

if [ -z "${BUILD_PATH}" ]; then
	eerror "BUILD_PATH variable is empty. Exiting."
	exit 1
fi

if [ $(realpath "${BUILD_PATH}") = "/" -o "${BUILD_PATH}" = "/*" ]; then
	eerror "You can not set BUILD_PATH variable to root partition"
	exit 1
fi

einfo "Using kernel $(get_latest_kernel_version)"

eselect kernel set $(get_latest_kernel_id)

if [ -e "${BUILD_PATH}" ]; then
	rm -rf "${BUILD_PATH}"
fi
mkdir "${BUILD_PATH}"

zcat /proc/config.gz > "${BUILD_PATH}"/.config
